---
openapi: 3.0.0
info:
  title: ToDo Api
  description: ToDo API used to manage ToDos
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/zaher1307/ToDoAPI/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /todolist:
    get:
      tags:
      - todoList
      summary: Get todo list
      description: Retrieving todo list
      operationId: GetTodoItemsList
      responses:
        "200":
          description: All requests recieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/todoItem'
    post:
      tags:
      - todoList
      summary: Add a new todo item to the todo list
      operationId: AddTodoItem
      responses:
        "201":
          description: Request successeded and item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'
        "400":
          description: Invalid input, object is invalid
        "409":
          description: Anexisting item, already exists
  /todolist/{id}:
    get:
      tags:
      - todoItem
      summary: Get todo item by id
      operationId: GetTodoItemById
      parameters:
      - name: id
        in: path
        description: Id of todo Item
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 123456789
      responses:
        "200":
          description: Request recieved and is being processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'
        "404":
          description: Not found
    delete:
      tags:
      - todoItem
      summary: Delete an existing todo
      operationId: DeleteTodoItemById
      parameters:
      - name: id
        in: path
        description: Id of todo item
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Request recieved and is being processed
        "400":
          description: Did not understand the request
        "404":
          description: Not found
    patch:
      tags:
      - todoItem
      summary: Update an existing todo
      operationId: UpadateTodoItemById
      parameters:
      - name: id
        in: path
        description: Id of todo item
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "201":
          description: Request recieved and is being processed
        "400":
          description: Did not understand the request
        "404":
          description: Not found
components:
  schemas:
    todoItem:
      required:
      - completed
      - id
      - todoItem
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123456789
        todoItem:
          type: string
          example: clean the room
        completed:
          type: boolean
          example: false
