name: Todo backend tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:
  code_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: go test
      run: |
        cd todo-backend
        go test *.go
    
    - name: build and run docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zaher1307/todo-docker
        registry: docker.io
        directory: backend
        dockerfile: backend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
